spring:
  datasource:
    url: jdbc:mysql://localhost:3307/uniclub
    username: root
    password: tuan2006
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none


