spring:
  datasource:
    url: jdbc:mysql://localhost:3307/uniclub
    username: root
    password: tuan2006
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none

secret-key:
  jwt: OVsGlq1Ws7mgqImxilMf9AwAw0NwU6vnWtQv7bbuLqs=

upload:
  image: C:\Users\bopbi\Downloads\Upload
